export const ROUTES = {
  INIT: "/",
  WELCOME: "/user",
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  VERIFY_FORGOT_PASSWORD: "/auth/forgotPw/",
  REGISTER: "/register",
  REGISTER_SUCCESS: "/register-success",
  ACTIVE_ACCOUNT: "/auth/active/:token",
  FORGOT_PASSWORD_NOITICE: "/verify-reset-password",
  CHANGE_PASSWORD: "/change-password",
  CHANGE_PASSWORD_SUCCESS: "/change-password/success",

  /////// LOGIN IN ////////////
  SELECT_STORE: "/select-store",
  DETAIL_STORE: "/store/:id",
  DASHBOARD: "/dashboard",
  STORE_REFERENCES: "/store-preference",
  CREATE_QR: "/create-qr",
  OPENING_HOURS: "/openings-hours",
  CATEGORY_SETTING: "/category-setting",
  ADD_OPTIONS: "/add-options",
  MENU_SETTING: "/menu-setting",
  STAFF_REGISTRATION: "/staff-registration",
  ORDER_LIST: "/order-list",
  ALERT_LIST: "/alert-list",
  STATISTICS: "/statistics",
  CUSTOMER_CENTER: "/customer-center",
  PROFILE: "/profile",
};
